{
    "name": "Sale Order Vendor Bills",
    "version": "1.0",
    "depends": ["sale", "account"],
    "author": "Generated by ChatGPT",
    "category": "Sales",
    "description": "Adds a one2many field in Sale Order to link related Vendor Bills (account.move).",
    "data": [
        "views/sale_order_view.xml"
    ],
    "installable": True,
    "application": False,
}
